### ISSUE TITLE
App Division

### ISSUE THREAD

**Issue by narayanaditya95** [Robotix/RobotixApp#2]
I propose a division of our existing app into 3 different apps.
- Tutorial App
- Event App
- Fest App (The major app, the Robotix app)

This would allow us to roll out updates to the fest app on a weekly basis while Tutorial and Event app would only receive bug fixes. The tutorial and event app will use Github's API to communicate with our website. Thus, they do not need yearly updates.
The Fest App will be the central app with link to team, location, FAQs.
All apps will share the same sidebar. Clicking on events icon on the fest app will open up the Event app or redirect the user to Play store for a download.

@sam17 @abhinavjain241 @ManashRaja Suggestions for the proposal.

**Comment by sam17** [comment]
What do you mean by 3 diff apps?

On Fri, 4 Sep 2015 at 19:29 Aditya Narayan <notifications@github.com> wrote:

> I propose a division of our existing app into 3 different apps.
>
>    - Tutorial App
>    - Event App
>    - Fest App
>
> This would allow us to roll out updates to the fest app on a weekly basis
> while Tutorial and Event app would only receive bug fixes. The tutorial and
> event app will use Github's API to communicate with our website. Thus, they
> do not need yearly updates.
> The Fest App will be the central app with link to team, location, FAQs.
> All apps will share the same sidebar. Clicking on events icon on the fest
> app will open up the Event app or redirect the user to Play store for a
> download.
>
> @sam17 <https://github.com/sam17> @abhinavjain241
> <https://github.com/abhinavjain241> @ManashRaja
> <https://github.com/ManashRaja> Suggestions for the proposal.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Robotix/RobotixApp/issues/2>.
>
-- 
Soumyadeep Mukherjee
Final year Undergraduate Student
IIT Kharagpur
Ph No.: +91 7407651462
Webpage:
http://www.kyb.tuebingen.mpg.de/nc/employee/details/smukherjee.html#=0

**Comment by narayanaditya95** [comment]
@sam17 Three different app that can be installed independently and invoked from one another.
This has been the trend to cater to different audience and minimise the app size for each.
See [Housing](https://play.google.com/store/apps/developer?id=Housing&hl=en) and [Aasaanjobs](https://play.google.com/store/apps/dev?id=6106200181380868600&hl=en).
A non-participating student can install the tutorial app and never bother about the fest or the event app.

This is just a suggestion and is liable for further discussion.

**Comment by sam17** [comment]
No. We don't want us. We want to be flipkart. We enforce them to see it all
and get all updates so that we push them to do what we desire. :P

On Fri, 4 Sep 2015 at 19:37 Aditya Narayan <notifications@github.com> wrote:

> @sam17 <https://github.com/sam17> Three different app that can be
> installed independently and invoked from one another.
> This has been the trend to cater to different audience and minimise the
> app size for each.
> See Housing
> <https://play.google.com/store/apps/developer?id=Housing&hl=en> and
> Aasaanjobs
> <https://play.google.com/store/apps/dev?id=6106200181380868600&hl=en>.
> A non-participating student can install the tutorial app and never bother
> about the fest or the event app.
>
> This is just a suggestion and is liable for further discussion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Robotix/RobotixApp/issues/2#issuecomment-137746350>.
>
-- 
Soumyadeep Mukherjee
Final year Undergraduate Student
IIT Kharagpur
Ph No.: +91 7407651462
Webpage:
http://www.kyb.tuebingen.mpg.de/nc/employee/details/smukherjee.html#=0

**Comment by abhinavjain241** [comment]
I would also prefer a single app, since in my personal opinion, I don't think the targeted audience will be downloading 3 different apps. Let's have subtabs. The API calls can be still separate for different sections of the app.

**Comment by ManashRaja** [comment]
Abhinav, I didn't understand the different api calls thing.

**Comment by abhinavjain241** [comment]
@ManashRaja : As @narayanaditya95 mentioned, the tutorial and event apps would use GitHub API to communicate with the website. And the fest app will be the one which will be calling the REST API/Parse SDK, whatever may be in place to get regular updates regarding the fest. So I propose, to have a single app, but include the functionality of all three in it. 

It is possible that you can call different API's from the same app, right?
