### ISSUE TITLE
Google Material Design Update

### ISSUE THREAD

**Issue by narayanaditya95** [Robotix/RobotixApp#3]
Our website is responsive and adhere to most of the google design principles.
Our new app must resemble our UI on the website to minimise any learning curve for its use.

@ManashRaja Does this require a complete app rewrite?
@sam17 @abhinavjain241 Suggestions?

**Comment by ManashRaja** [comment]
@narayanaditya95 Ya, will have to rewrite the whole app. Not from ground up though, as I the pages and content will remain somewhat the same and only the layout will change.
